server/config/routes.rb
Bestmix::Application.routes.draw do
  get "my_posts/index"

  get "my_posts/create"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Doorkeeper::Engine => '/oauth'

  get 'oauth/token' => 'doorkeeper/tokens#create'

  devise_for :users

  namespace :api do
    api_version(:module => "V1", :path => "/v1") do
      resources :posts, :only => [ :index, :show ]
      resources :my_posts, :except => [ :edit ]
      resources :users, :only => [ :show ]
    end
  end

  resources :posts
  resources :my_posts

  root :to => 'main#index'

end

server/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    page = (params[:page] || 1).to_i

    if user_signed_in?
      @my_posts = current_user.posts.page(page)
    end

    @public_posts = Post.published.page(page)
  end
end

server/app/helpers/main_helper.rb
module MainHelper
end

server/app/views/main/index.html.haml
.row
  .column.span9
    - if @public_posts.empty?
      no post
    - else
      - @public_posts.each do |post|
        .post
          %h2.title= post.title
          .content= post.content
          .published
            %span= post.published_at.to_s
            %span= post.user.email

  .column.span3
    %header.page-header
      %h2 Blog App
    - unless user_signed_in?
      Please
      = link_to "sign in", new_user_session_path
      to compose your blog entries.
    - else
      %p= link_to "Compose", my_posts_path, :class => "btn btn-primary"