server/config/routes.rb
Bestmix::Application.routes.draw do
  get "my_posts/index"

  get "my_posts/create"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Doorkeeper::Engine => '/oauth'

  get 'oauth/token' => 'doorkeeper/tokens#create'

  devise_for :users

  namespace :api do
    api_version(:module => "V1", :path => "/v1") do
      resources :posts, :only => [ :index, :show ]
      resources :my_posts, :except => [ :edit ]
      resources :users, :only => [ :show ]
    end
  end

  resources :posts
  resources :my_posts

  root :to => 'main#index'

end

server/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

server/app/models/api_error.rb
class ApiError
  attr_accessor :error, :error_description, :messages

  def self.json(error, error_description, messages)
    self.new(error, error_description, messages).to_json
  end

  def initialize(error, error_description, messages)
    @error = error
    @error_description = error_description
    @messages = messages
  end
end

server/app/models/facebook_user.rb
class FacebookUser
  attr_accessor :id, :name, :first_name, :last_name, :username, :gender

  def initialize(hash = {})
    @hash = hash
  end

  def id
    @hash[:id.to_s]
  end

  def name
    @hash[:name.to_s]
  end

  def first_name
    @hash[:first_name.to_s]
  end

  def last_name
    @hash[:last_name.to_s]
  end

  def username
    @hash[:username.to_s]
  end

  def gender
    @hash[:gender.to_s]
  end

  def inspect
    @hash.inspect
  end
end

server/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :published_at, :title, :publish

  attr_accessor :publish

  belongs_to :user

  validates :title, :presence => true, :length => { :minimum => 3, :maximum => 255 }
  validates :content, :length => { :minimum => 0, :maximum => 10000 }

  before_save :set_published_at

  scope :published, where("published_at IS NOT NULL")

  scope :alive, where("deleted_at IS NULL")

  scope :my, lambda { |user|
    where(:user_id => user.id).order("updated_at DESC")
  }

  scope :accessible, lambda { |user|
    where("user_id = ? OR published_at IS NOT NULL", user.id)
  }

  def published
    published_at != nil
  end

  def deleted
    deleted_at != nil
  end

  private

  def set_published_at
    if (publish == true || publish == "true" || publish == "1") && published_at.nil?
      self.published_at = Time.now
    elsif (publish != true && publish != "true" && publish != "1") && published_at
      self.published_at = nil
    end
  end
end

server/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  attr_accessible :provider, :uid

  attr_accessor :facebook_user

  has_many :posts, :dependent => :destroy

  has_many :access_grants, :dependent => :destroy, :class_name => "Doorkeeper::AccessGrant", :foreign_key => "resource_owner_id"
  has_many :access_tokens, :dependent => :destroy, :class_name => "Doorkeeper::AccessToken", :foreign_key => "resource_owner_id"

  # validates_presence_of   :email, :if => :email_required?
  # validates_uniqueness_of :email, :allow_blank => true, :if => :email_changed?
  # validates_format_of     :email, :with  => email_regexp, :allow_blank => true, :if => :email_changed?

  # validates_presence_of     :password, :if => :password_required?
  # validates_confirmation_of :password, :if => :password_required?
  # validates_length_of       :password, :within => password_length, :allow_blank => true

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create(
        # name: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end

    if user.valid?
      user.facebook_token = auth.credentials.token
      user.facebook_expires_at = Time.at(auth.credentials.expires_at)
      user.save
    end

    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def facebook
    if !@facebook && facebook_token && facebook_expires_at > Time.now
      @facebook = Koala::Facebook::API.new(facebook_token)
    end
    @facebook
  end
end

server/app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  # include Doorkeeper::Controller

  skip_before_filter :verify_authenticity_token

  respond_to :json

  def render_error(error, error_description, messages)
    render :json => ApiError.json(error, error_description, messages)
  end

  private

  def current_user
    if doorkeeper_token
      @current_user ||= User.find(doorkeeper_token.resource_owner_id)
    end
  end
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

server/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    page = (params[:page] || 1).to_i

    if user_signed_in?
      @my_posts = current_user.posts.page(page)
    end

    @public_posts = Post.published.page(page)
  end
end

server/app/controllers/my_posts_controller.rb
class MyPostsController < InheritedResources::Base
  defaults :resource_class => Post, :collection_name => 'posts', :instance_name => 'post'

  before_filter :authenticate_user!

  def create
    create! { my_posts_path }
    @post.user = current_user
    @post.save
  end

  def update
    update! { my_posts_path }
  end

  protected

  def begin_of_association_chain
    current_user
  end

  def collection
    @posts ||= end_of_association_chain.order("updated_at DESC")
    # @posts ||= end_of_association_chain.page((params[:page] || 1).to_i)
  end
end

server/app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      unless @user.valid?
        flash[:notice] = @user.errors.full_messages.join(". ") + "."
        redirect_to new_user_session_path
        return
      end
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_path
    end
  end
end

server/app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_filter :authenticate_user!

  def index
    redirect_to root_path
  end
end

server/app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

server/app/helpers/api/v1/my_posts_helper.rb
module Api::V1::MyPostsHelper
end

server/app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

server/app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/main_helper.rb
module MainHelper
end

server/app/helpers/my_posts_helper.rb
module MyPostsHelper
end

server/app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

server/app/helpers/posts_helper.rb
module PostsHelper
end

server/app/views/doorkeeper/authorizations/error.html.erb
<div class="span12">
  <h2>An error has occurred</h2>
  <p>
    <pre><%= @error.description %></pre>
  </p>
</div>

server/app/views/doorkeeper/authorizations/new.html.erb
<header class="page-header"><h2>Authorize <%= @authorization.client.name %> to use your account?</h2></header>

<div class="row">
  <div class="well span12">
    <% if @authorization.scopes %>
    <p>
      This application will be able to:
    </p>
    <ul>
      <% @authorization.scopes.each do |scope| %>
        <li><%= t scope, :scope => [:doorkeeper, :scopes]  %></li>
      <% end %>
    </ul>
    <% end %>

    <div class="inline_block">
      <%= form_for @authorization, :as => :authorization, :url => authorization_path, :method => :post do |f| %>
        <%= f.hidden_field :client_id %>
        <%= f.hidden_field :redirect_uri %>
        <%= f.hidden_field :state %>
        <%= f.hidden_field :response_type %>
        <%= f.hidden_field :scope %>
        <%= f.submit "Authorize", :class => "btn btn-success" %> or
      <% end %>
    </div>
    <div class="inline_block">
      <%= form_for @authorization, :as => :authorization, :url => authorization_path, :method => :delete do |f| %>
        <%= f.hidden_field :client_id %>
        <%= f.hidden_field :redirect_uri %>
        <%= f.hidden_field :state %>
        <%= f.hidden_field :response_type %>
        <%= f.hidden_field :scope %>
        <%= f.submit "Deny", :class => "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

server/app/views/doorkeeper/authorized_applications/index.html.erb
<header class="page-header"><h2>Your authorized applications</h2></header>

<div class="row">
  <table class="table table-bordered table-striped span12">
    <thead>
      <tr>
        <th>Application</th>
        <th>Authorized at</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @applications.each do |application| %>
        <tr>
          <td style="vertical-align: middle;"><%= application.name %></td>
          <td style="vertical-align: middle;"><%= application.created_at %></td>
          <td style="vertical-align: middle;"><%= link_to 'Revoke', authorized_application_path(application), :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

server/app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %meta{ :charset => "utf-8" }
    %title Bestmix
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "bootstrap-responsive.css", :media => "all"
    /[if lt IE 9]
      %script{ :src => "http://html5shim.googlecode.com/svn/trunk/html5.js" }
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{ :type => "button", "data-toggle" => "collapse", "data-target" => ".nav-collapse" }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Bestmix Admin", "/admin", :class => "brand"
          %ul.nav.pull-right
            - if admin_user_signed_in?
              %li= link_to current_admin_user.email, "/admin"
              %li= link_to "Logout", "/admin/logout", :method => :delete
            - else
              %li= link_to "Login", "/admin/login"
          .nav-collapse.collapse
            %ul.nav.pull-right
              %li= link_to "Dashboard", "/admin"
              %li= link_to "Access Grants", "/admin/doorkeeper_access_grants"
              %li= link_to "Access Tokens", "/admin/doorkeeper_access_tokens"
              %li= link_to "Posts", "/admin/posts"
              %li= link_to "Users", "/admin/users"
              %li= link_to "Applications", "/oauth/applications"
    .container
      .row
        - flash.each do |key, message|
          .span12
            .alert.alert-block{ :class => key }
              %a.close{ :href => "#", "data-dismiss" => "alert" } &times;
              = message
      = yield

server/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ :charset => "utf-8" }
    %title Bestmix
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "bootstrap-responsive.css", :media => "all"
    /[if lt IE 9]
      %script{ :src => "http://html5shim.googlecode.com/svn/trunk/html5.js" }
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          - if user_signed_in?
            %button.btn.btn-navbar{ :type => "button", "data-toggle" => "collapse", "data-target" => ".nav-collapse" }
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          = link_to "Bestmix", "/", :class => "brand"
          %ul.nav.pull-right
            - if user_signed_in?
              %li= link_to '@' + current_user.email.sub(/@.*\Z/, ''), "/users/edit"
              %li= link_to "Sign out", "/users/sign_out", :method => :delete
            - else
              %li= link_to "Sign in", "/users/sign_in"
              %li= link_to "Sign up", "/users/sign_up"
          - if user_signed_in?
            .nav-collapse.collapse
              %ul.nav.pull-right
                %li= link_to "Home", "/"
                %li= link_to "My Posts", "/my_posts"
                %li= link_to "Apps", "/oauth/authorized_applications"
    .container
      .row
        - flash.each do |key, message|
          .span12
            .alert.alert-block{ :class => key }
              %a.close{ :href => "#", "data-dismiss" => "alert" } &times;
              = message
      = yield