server/config/routes.rb
Bestmix::Application.routes.draw do
  get "my_posts/index"

  get "my_posts/create"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Doorkeeper::Engine => '/oauth'

  get 'oauth/token' => 'doorkeeper/tokens#create'

  devise_for :users

  namespace :api do
    api_version(:module => "V1", :path => "/v1") do
      resources :posts, :only => [ :index, :show ]
      resources :my_posts, :except => [ :edit ]
      resources :users, :only => [ :show ]
    end
  end

  resources :posts
  resources :my_posts

  root :to => 'main#index'

end

server/app/controllers/api/v1/my_posts_controller.rb
class Api::V1::MyPostsController < Api::ApiController
  doorkeeper_for :all

  def index
    page = (params[:page] || 1).to_i
    expires_in 5.seconds
    if page > 1 || stale?(last_modified: current_user.posts.maximum(:updated_at))
      @posts = current_user.posts.alive.order("updated_at DESC").page(page)
    end
  end

  def show
    @post = current_user.posts.find_by_id(params[:id])
    if @post.nil?
      render_error(
        :resource_not_found,
        "Not Found",
        "Requested post does not exist or you don't have permission to see it."
      )
      return
    end
    expires_in 5.seconds
    fresh_when @post
  end

  def create
    @post = current_user.posts.create(params[:post])
    unless @post.valid?
      render_error(:invalid_parameter, "Parameter Error", @post.errors.messages)
      return
    end
    render :action => :show
  end

  def update
    @post = current_user.posts.find_by_id(params[:id])
    @post.update_attributes(params[:post])
    unless @post.valid?
      render_error(:invalid_parameter, "Parameter Error", @post.errors.messages)
      return
    end
    render :action => :show
  end

  def destroy
    @post = current_user.posts.find_by_id(params[:id])
    @post.update_attribute(:deleted_at, Time.now)
    render :action => :show
  end
end

server/app/controllers/my_posts_controller.rb
class MyPostsController < InheritedResources::Base
  defaults :resource_class => Post, :collection_name => 'posts', :instance_name => 'post'

  before_filter :authenticate_user!

  def create
    create! { my_posts_path }
    @post.user = current_user
    @post.save
  end

  def update
    update! { my_posts_path }
  end

  protected

  def begin_of_association_chain
    current_user
  end

  def collection
    @posts ||= end_of_association_chain.order("updated_at DESC")
    # @posts ||= end_of_association_chain.page((params[:page] || 1).to_i)
  end
end

server/app/helpers/api/v1/my_posts_helper.rb
module Api::V1::MyPostsHelper
end

server/app/helpers/my_posts_helper.rb
module MyPostsHelper
end

server/app/views/my_posts/_form.html.haml
.row
  .span12
    = form_for(@post, :url => (@post.id ? my_post_path(@post) : my_posts_path), :html => { :class => "well" }) do |f|
      - if @post.errors.any?
        #error_explanation
          %h2
            = pluralize(@post.errors.count, "error")
            prohibited this post from being saved:
          %ul
            - @post.errors.full_messages.each do |msg|
              %li= msg

      = f.label :title
      = f.text_field :title, :style => "width: 99%;"

      = f.label :content
      = f.text_area :content, :style => "width: 99%;"

      %label.checkbox{ :for => "post_publish" }
        - @post.publish = @post.published if @post.publish.nil?
        - @post.publish = true unless @post.created_at
        = f.check_box :publish
        Publish

      %button{ :type => "submit", :class => "btn" } Save

server/app/views/my_posts/edit.html.haml
%header.page-header
  %h2 Editing Post

= render 'form'

.row
  %p.span12= link_to 'Back', my_posts_path

server/app/views/my_posts/index.html.haml
%header.page-header
  %h2 My Posts

.row
  .span12
    %p= link_to 'New Post', new_my_post_path, :type => "submit", :class => "btn"

.row
  %table.table.table-bordered.table-striped.span12.my-post
    - @posts.each do |post|
      %tr
        %td
          .title= post.title
          .content= post.content
          .published
            - if post.published_at
              published at
              = post.published_at.to_s(:db)
            - else
              %i not published yet
          .tasks
            = link_to 'Edit', edit_my_post_path(post)
            = link_to 'Destroy', my_post_path(post), data: { confirm: 'Are you sure?' }, method: :delete

server/app/views/my_posts/new.html.haml
%header.page-header
  %h2 New Post

= render 'form'

.row
  .span12= link_to 'Back', my_posts_path